### ISSUE TITLE
Expected capacity of the solr package is unknown

### ISSUE THREAD

**Issue by areuser** [ropensci/solr#47]
Using the solr package for medium size datasets (5000+ observations;30+ variables) is quite a stretch. I therefore wonder what size of datasets your targeting at.

**Comment by sckott** [comment]
@areuser to be honest, I haven't tested with a very wide variety of datasets. I should!

> Using the solr package for medium size datasets (5000+ observations;30+ variables) is quite a stretch.

Is quite a stretch for what functionality of the package?  Specific functions? Can you give examples?

**Comment by areuser** [comment]
Thanks for your quick response. 

**The context**
One of my  smaller datasets contains 4 million observations of 30 variables each. Samples of 5000 observations are used to determine correlations between the variables. 

**The issue**

Extracting a sample from apache solr takes 1.2 seconds. 
Extracting a sample from R package solr takes 24 takes. 

```
sample <- solr_search(q='*:*', rows=5000)
```

**Comment by sckott** [comment]
Hi @areuser - I see what you  mean. I'm profiling the function now. Since `solr` by default attempts to parse the returned data into familiar R data.frame's, this data.frame creation is the slow part. I will try to speed that up - the fast options (`data.table`, `dplyr`) are usually not very general though, we'll see. 

Another option is to set `raw=TRUE`, which gives you back the raw json or xml. e.g., (using 30 variables as you said, requesting 5000 records)

```r
url <- 'http://api.plos.org/search'
fields <- c('id','cross_published_journal_name','cross_published_journal_key',
            'cross_published_journal_eissn','pmid','pmcid','publisher','journal',
            'journal_id_pmc','journal_id_publisher','journal_id_nlm_ta','eissn',
            'publication_date','article_type','article_type_facet','author',
            'author_facet','volume','issue','elocation_id','author_display',
            'author_without_collab_display','competing_interest','copyright',
            'abstract','abstract_primary_display','title_display','title',
            'alternate_title','figure_table_doi')
system.time(out <- solr_search(q='*:*', rows=5000, fl=fields, base=url, raw = TRUE))
#> user  system elapsed 
#>   0.208   0.102   5.984 
```

This same call with `raw=FALSE` (parsing to a data.frame) takes about 20 seconds. So similar to what you got.

**Comment by sckott** [comment]
@areuser Okay, reinstall from master branch, like `install_github("ropensci/solr")`, then try your example again. You should get a time that's quite a bit faster, based on using `dplyr` to do parsing. You can of course just get the raw data back and parse yourself. Let me know what you think. I will try to increase speed even more, but that creation of data.frame step was the slowest part.

**Comment by areuser** [comment]
Processing time required has indeed decreased significantly. It's quite a bit faster.
I'm using data.frames to create prediction and classification models. A potential increase of the sample size would increase the precision of the model. My current datasets are between 4 million and 1 billion observations.   

The current processing time of a sample of 5.000 observations.
```
 system.time(response <-  solr_search(q='*:*', rows=5000,...))
# user  system elapsed 
# 6.851   0.000   7.534 
```
I was therefore wondering whether it was possible to reach 2.4 seconds for 5.000 observations?

**Comment by sckott** [comment]
@areuser I'll see if I can match that.

**Comment by sckott** [comment]
I think hadley said `httr` by default uses compression, but I'll look into that. 

Okay, I pushed a new branch to work on some speed things, Install like `install_github("ropensci/solr@faster")`. It's just a small fix to try to make csv parsing more general. Does your Solr instance allow `wt=csv` ? If so, that is faster than `wt=json`. e.g, using my example from above

```r
system.time(out <- solr_search(q='*:*', rows=5000, fl=fields, base=url, wt = "json"))
#>   user  system elapsed 
#>  5.010   0.158  10.914 

system.time(out <- solr_search(q='*:*', rows=5000, fl=fields, base=url, wt = "csv"))
#>   user  system elapsed 
#>  0.211   0.055   3.860 
```

**Comment by sckott** [comment]
I played around with using the ability in `jsonlite` to parse json directly to a data.frame, but you get nested lists within the data.frame, which are a pain to deal with, and anyway, using gains very little speed compared to parsing json to a list, then lists to a data.frame as we currently do.  

There are a few minor things I can try to speed up with some trial and error, but I think the csv option will be the biggest gain as long as your Solr engine allows csv output

**Comment by areuser** [comment]
You've nailed it! The csv option improves the capacity of solr_search considerably. 
So in the end it's all about configuration and a bit of smarts. Thanks for the effort.

**Comment by sckott** [comment]
@areuser great! I thought csv support hadn't been around very long, but perhaps it has. Do you know?  If it has been in Solr for many versions, I could make `wt=csv` the default to increase speed when going directly to a data.frame output.

**Comment by areuser** [comment]
Time flies when your having fun. Probably it's best to set it as the default because, based on my poor memory, it's already part of solr from 3.1 onwards.

**Comment by sckott** [comment]
Thanks, will try that, #48

**Comment by sckott** [comment]
@areuser looks like httr does add an `Accept-Encoding: gzip` header by default, so you shouldn't need to in `solr`

vs. using curl which doesn't

```r
<r> GET("http://api.plos.org/search?q=*:*&wt=json", verbose())
-> GET /search?q=*:*&wt=json HTTP/1.1
-> User-Agent: curl/7.37.1 Rcurl/1.95.4.5 httr/0.6.1
-> Host: api.plos.org
-> Accept-Encoding: gzip
-> Accept: application/json, text/xml, application/xml, */*
```

```sh
curl -v 'http://api.plos.org/search?q=*:*&wt=json'

* Hostname was NOT found in DNS cache
*   Trying 149.20.69.12...
* Connected to api.plos.org (127.0.0.1) port 80 (#0)
> GET /search?q=*:*&wt=json HTTP/1.1
> User-Agent: curl/7.37.1
> Host: api.plos.org
> Accept: */*
```

**Comment by areuser** [comment]
Thanks for your guidance on this. It seems compression needs to added to the container of solr before it's actually used. In my case the container is tomcat.

```
<Connector executor="tomcatThreadPool"
               port="8100" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443" 
               compression="on"
               compressionMinSize="2048"
               compressableMimeType="text/plain" />
```

**Comment by sckott** [comment]
Right, good point that compression needs to be turned on server side, I should make notes about this in the client in case they haven't though about compression
