### ISSUE TITLE
Change pkg name

### ISSUE THREAD

**Issue by sckott** [ropensci/solr#74]
@ropensci/owners any objections to changing the package name?  Since it's currently the name of the thing it wraps, it's not great, esp for searching for uses of this pkg, an a bit confusing

It is already on CRAN as `solr` https://cran.rstudio.com/web/packages/solr/, but only 1 version there so far. Seems like we could change name and submit as a new package since it sounds like CRAN won't allow a name change https://stat.ethz.ch/pipermail/r-devel/2013-August/067264.html and keep `solr` up, or maybe request that they take it down. 

this pkg only used by one other on CRAN, and that's `rplos`, so that's easy to take care of, just depend on the new pkg name in `rplos`

possible names:

* `apollo` (greek sun god)
* `helios` (another greek sun god-esque character)
* `solrflare`
* others?

**Comment by karthik** [comment]
New name sounds good.

**Comment by sckott** [comment]
:smiley_cat:
